version: '3'
services:
  megalinter_server_redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  megalinter_server_api:
    image: megalinter-server:latest
    command: uvicorn server.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - megalinter_server_redis
    links:
      - megalinter_server_redis
  megalinter_server_worker:
    image: ghcr.io/oxsecurity/megalinter-ci_light:alpha
    #image: ghcr.io/oxsecurity/megalinter-cupcake:alpha
    environment:
      - MEGALINTER_SERVER=true
    depends_on:
      - megalinter_server_redis
    links:
      - megalinter_server_redis